@validToken = ""

###active_2fa: active 2fa per id or email
# @prompt idOrEmail
POST http://localhost:8080/users/2fa/active/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}
