@validToken = ""

###change_password: change password of user per id or email
# @prompt idOrEmail
PUT http://localhost:8080/users/changeEmail/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}

{
  "Code": "123456",
	"Email": "newFulano@fulano.com"
}