###change_password_in_recovery
# @prompt idOrEmail
POST http://localhost:8080/users/changePasswordInRecovery/{{idOrEmail}}
content-type: application/json

{
	"Code": "123456",
  "NewPassword": "aaaaaA#7"
}