@validToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImZ1bGFub0BmdWxhbm8uY29tIiwiSWQiOjEsImV4cCI6MTcxMDk0MzYyMn0.y5M0hz0gy5TFSAJD3AvykUBPw0m0l8NmOqBuDOgNwfI

###change_password: change password of user per id or email
# @prompt idOrEmail
PUT http://localhost:8080/user/changePassword/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}

{
	"Password": "aaaaasadzxcasdA#7"
}