@validToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImZ1bGFub0BmdWxhbm8uY29tIiwiSWQiOjEsImV4cCI6MTcxMDk0MzYyMn0.y5M0hz0gy5TFSAJD3AvykUBPw0m0l8NmOqBuDOgNwfI

###find_user: find user per id or email
# @prompt idOrEmail
GET http://localhost:8080/users/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}
