@validToken = ""

###verify_email
# @prompt idOrEmail
POST http://localhost:8080/users/verifyEmail/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}

{
	"Code": "123456"
}