@validToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IlRFU1RAVEVTVC5jb20iLCJJZCI6MSwiSXNBZG1pbiI6dHJ1ZSwiZXhwIjoxNzEyMzQwMTQ0fQ.GTv6h9rVwoyPz1jLTHJFapMbsvGATnXukhmnrUIaT_0

###admin_find_all_logs
GET http://localhost:8080/admin/logs
content-type: application/json
Authorization: Bearer {{validToken}}
