@validToken = ""

###admin_inative_user: find user per id or email
# @prompt idOrEmail
POST http://localhost:8080/admin/users/inative/{{idOrEmail}}
content-type: application/json
Authorization: Bearer {{validToken}}
