info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create User
      tags:
      - user
swagger: "2.0"
