name: go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: "latest"

  build:
    name: Build
    needs: lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Run Go Build
        run: go build

  test:
    name: Test
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Run Tests
        run: go test -p 1 ./src/...
