name: go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: "latest"

  build:
    name: Build
    needs: lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Run Go Build
        run: go build

  test:
    name: Test
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Run Tests
        run: go test -p 1 ./src/...

  load_testing:
    name: load testing
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Set Environment Variable
        run: echo "ENV=test" >> $GITHUB_ENV

      - name: Install Vegeta
        run: go get -u github.com/tsenart/vegeta

      - name: Exec load test with Vegeta
        run: |
          echo "GET http://localhost:8080/" | vegeta attack -duration=30s | tee results.bin | vegeta report
